/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:0dfd3290-9e34-4844-83d2-691410c0c968",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_Eiz571NU4",
    "aws_user_pools_web_client_id": "7v3k63v0p1vh1jlnj3o26do9jp",
    "oauth": {
        "domain": "nuchbee-auth-dev.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://nuchbee-auth-dev.auth.ap-south-1.amazoncognito.com/",
        "redirectSignOut": "https://nuchbee-auth-dev.auth.ap-south-1.amazoncognito.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
